// Post-processes `expo export -p web` output (dist/) into an installable,
// offline-capable PWA for GitHub Pages:
//   1. injects manifest/theme/apple-touch tags + service-worker registration
//      into dist/index.html
//   2. generates dist/sw.js with a precache list of every exported file
// Run after every export: `node scripts/postbuild-web.js`

const fs = require('fs');
const path = require('path');

const BASE = '/LukesTracker'; // must match app.json experiments.baseUrl
const DIST = path.join(__dirname, '..', 'dist');

// --- collect every exported file for the precache list ---------------------
function walk(dir, out = []) {
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    const p = path.join(dir, entry.name);
    if (entry.isDirectory()) walk(p, out);
    else out.push(p);
  }
  return out;
}

const files = walk(DIST)
  .map((p) => path.relative(DIST, p))
  .filter((p) => p !== 'sw.js')
  .map((p) => `${BASE}/${p.split(path.sep).join('/')}`);
// The navigation URL itself.
files.unshift(`${BASE}/`);

// Cache name keyed by content of the JS bundle list so a new deploy busts it.
const version = require('crypto')
  .createHash('sha1')
  .update(files.join('\n'))
  .digest('hex')
  .slice(0, 12);

// --- service worker ---------------------------------------------------------
const sw = `// Generated by scripts/postbuild-web.js — do not edit by hand.
const CACHE = 'lukestracker-${version}';
const PRECACHE = ${JSON.stringify(files, null, 2)};

self.addEventListener('install', (event) => {
  event.waitUntil(
    caches.open(CACHE).then((cache) => cache.addAll(PRECACHE)).then(() => self.skipWaiting())
  );
});

self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches.keys().then((keys) =>
      Promise.all(keys.filter((k) => k !== CACHE).map((k) => caches.delete(k)))
    ).then(() => self.clients.claim())
  );
});

self.addEventListener('fetch', (event) => {
  if (event.request.method !== 'GET') return;
  const url = new URL(event.request.url);
  if (url.origin !== self.location.origin) return;

  event.respondWith(
    caches.match(event.request, { ignoreSearch: true }).then((hit) => {
      if (hit) return hit;
      return fetch(event.request)
        .then((res) => {
          if (res.ok) {
            const copy = res.clone();
            caches.open(CACHE).then((cache) => cache.put(event.request, copy));
          }
          return res;
        })
        .catch(() => {
          // Offline navigation falls back to the app shell.
          if (event.request.mode === 'navigate') {
            return caches.match('${BASE}/');
          }
          return undefined;
        });
    })
  );
});
`;
fs.writeFileSync(path.join(DIST, 'sw.js'), sw);

// --- index.html injection ----------------------------------------------------
const indexPath = path.join(DIST, 'index.html');
let html = fs.readFileSync(indexPath, 'utf8');

const headTags = [
  `<link rel="manifest" href="${BASE}/manifest.webmanifest"/>`,
  `<meta name="theme-color" content="#000000"/>`,
  `<link rel="apple-touch-icon" href="${BASE}/icons/apple-touch-icon.png"/>`,
  `<meta name="apple-mobile-web-app-capable" content="yes"/>`,
  `<meta name="mobile-web-app-capable" content="yes"/>`,
  `<meta name="apple-mobile-web-app-status-bar-style" content="black-translucent"/>`,
  `<meta name="apple-mobile-web-app-title" content="Lukes Tracker"/>`,
].join('');

const swScript = `<script>if('serviceWorker' in navigator){window.addEventListener('load',function(){navigator.serviceWorker.register('${BASE}/sw.js',{scope:'${BASE}/'});});}</script>`;

if (!html.includes('rel="manifest"')) {
  html = html.replace('</head>', `${headTags}</head>`);
}
if (!html.includes('serviceWorker')) {
  html = html.replace('</body>', `${swScript}</body>`);
}
fs.writeFileSync(indexPath, html);

console.log(`postbuild-web: ${files.length} files precached, cache ${version}`);
